### ISSUE TITLE
SVG.Gradient type gets overwritten when adopting it

### ISSUE THREAD

**Issue by Fuzzyma** [svgdotjs/svg.js#606]
In the SVG.Gradient constructor a type is set. But when you adopt a gradient this type gets overwritten.<s> The question is: Why is that so? The type is only set in the adopter and nowhere else (except for gradient). So when you create an element by hand (e.g. `draw.rect()`) it will never have a type. But as soon as you adopt this element somewhere a type gets added. Why is that so? Is this needed?</s> <-- wrong

**TODO:**
- [x] remove type assignment in adopter
- [x] remove type assignment in Gradient constructor
- [x] fix all occurences of radial/linear to radialGradient/linearGradient

**Comment by wout** [comment]
Passing the gradient type in the constructor was a design choice to keep things small and simple in the beginning, but we are well beyond that point now. The time is right to give both gradient types their respective classes I think. That will solve this issue.

In the beginning, I did a similar thing with circle/ellipse. Initially, I didn't implement `SVG.Circle`. The `circle()` method would return an instance of `SVG.Ellipse`.

**Comment by Fuzzyma** [comment]
I see no problem with having it that way. Actually I find it quite elegant to have it that way.
However: When the type is set, it should be linearGradient and radialGradient to stay consistent.

Also: I figured, that setting the type in the adopter is not needed because its done in the SVG.Element constructor already. So that line could be removed.

Furthermore when we change the gradient type so it says linearGradient/radialGradient we need to change it in the code where it is used. However thats nothing difficult

**Comment by Fuzzyma** [comment]
Fixed in the [3.0 branch](https://github.com/svgdotjs/svg.js/tree/3.0.0)
