### ISSUE TITLE
Documentation 2.5

### ISSUE THREAD

**Issue by Fuzzyma** [svgdotjs/svg.js#629]
This is the issue thread to gather all documentation changes which needs to be made and are important to the changes which are coming in 2.5

- [x] Document SVG.Stop (#614)
- [x] Wrong documentation on SVG.Gradient and SVG.Pattern (#615)
- [x] Add svg.colorAt.js plugin to documentation (#555)
- [x] Add flip documentation to transform page (#628)
- [x] Clarifiy use of `dx` and `dy` when used with px/% (#524)
- [x] Add `SVG.Box`, `SVG.Box.transform()` and additional parameter for rbox() (#626)
- [x] Add flip on both axis (#619)
- [x] Allow the method font to be used like the method attr (#620) (one cannot get the full obj though...)
- [ ] <s>animate().during() not called when not calling start() (#583)</s> -> fixed
- [x] make events cancelable (#550) (added `event()` method)
- [x] remove reference to old fuse search
- [x] define the domain name in statify.php as `svgjs.com` instead of `svgdotjs.github.io`
- [x] document svg parser which often left confused users behind (#553)
- [x] update doc to say we can pass a parent param to SVG.select() (#633)

**Comment by Fuzzyma** [comment]
> Exactly what I was thinking too! So we'll have:
>
>    http://svgjs.com/
>    http://svgjs.com/2.5/
>    http://svgjs.com/2.4/
>
>That's going to be necessary.

I think we could use travis to automatically build the docs whenever something is pushed to the corresponding branch. That would be a lot easier to maintain then

**Comment by dotnetCarpenter** [comment]
I think creating a hook on github.com, whenever we push a new tag, e.g. 2.4.x or 2.5.x, is easier than using travis-ci.

**Comment by Fuzzyma** [comment]
Yes if that is easier I completely agree. Iam not so familiar with this tools.

**Comment by wout** [comment]
I am neither. If we can create a hook starting up de webserver (`npm run dev`), then create the static version (`curl http://localhost:8008/statify.php`) and move the contents of the newly generated `static` dir to the master branch, that would save some time and make it easier to make quick changes.

**Comment by wout** [comment]
BTW, just noticed the Algolia search is broken... no idea that happened.

**Comment by Fuzzyma** [comment]
The error is: fuse is not defined which means that it tries to use fuse and not angolia... weired

**Comment by wout** [comment]
No, that's my fault. There's still a reference to the old fuse search I forgot to delete will fix it with the next update next week.

This is a problem at Algolia. I Already contacted them.

![screen shot 2017-03-08 at 17 10 14](https://cloud.githubusercontent.com/assets/107324/23712131/3afee3f6-0422-11e7-9e8f-08bdc7fbdd72.png)

**Comment by wout** [comment]
The accidentally deleted our project so I had to add the new API key. But it's working again. And I also removed the old search.

**Comment by Fuzzyma** [comment]
Interesting case :D. I wonder if they would have realized that without your intervention ^^

**Comment by wout** [comment]
Weird to say the least! their exact words were:

> Sorry there was some confusion, and we deleted your configuration.

😳

**Comment by Fuzzyma** [comment]
I would like to release the 2.5 version tomorrow. However do you think the doc needs to be up to date when doing the release?

Furthermore: There is only one blocking issue left. #550 has a few suggestions on how to solve the issue. We dont need to do that for 2.5 but I would like to. So if you both find some time, take a look at leave a comment :)

**Comment by wout** [comment]
@Fuzzyma I'll further update the docs next week when I'm back in Spain (Thursday or Friday). I think you can release without updated docs. Next minor or major release we'll have to sync our agenda's though :)

In the meantime, shall I create a 2.4 branch of the current state and host it in the `svgjs.com/2.4/` sub-directory?

**Comment by Fuzzyma** [comment]
Yes 2.4 docs would be nice to have. But I wouldn't use the current state but the 2.4 tag of our master because that's the state you need when installing svgjs in version 2.4

**Comment by wout** [comment]
Done!

**Comment by dotnetCarpenter** [comment]
> If we can create a hook starting up de webserver (npm run dev), then create the static version (curl http://localhost:8008/statify.php) and move the contents of the newly generated static dir to the master branch, that would save some time and make it easier for quick changes.

@wout  I'd like to revisit this idea some time
